# Generated by Django 5.1.6 on 2025-02-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='max_close_friends_add',
            new_name='max_close_friends_allocation',
        ),
        migrations.AddField(
            model_name='user',
            name='current_allocation',
            field=models.IntegerField(default=0, help_text='The current number of space that this user has allocated to close friends'),
        ),
    ]
